export default {
	CURRENT_USER_RECIEVED: 'CURRENT_USER_RECIEVED',
	
	PROFILE_RECEIVED: 'PROFILE_RECEIVED',
	PROFILES_RECEIVED: 'PROFILES_RECEIVED',
	PROFILE_UPDDATED: 'PROFILE_UPDDATED',

	APPLICATIONS_RECEIVED: 'APPLICATIONS_RECEIVED',
	
	FETCH_POSTS: 'FETCH_POSTS',
	POSTS_RECEIVED: 'POSTS_RECEIVED',
	SAVED_POSTS_RECEIVED: 'SAVED_POSTS_RECEIVED',
	TEAM_POSTS_RECEIVED: 'TEAM_POSTS_RECEIVED',
	POST_CREATED: 'POST_CREATED',
	POST_UPDATED: 'POST_UPDATED',
	POST_SAVED: 'POST_SAVED',
	PROJECTS_RECEIVED: 'PROJECTS_RECEIVED',

	COMMENT_CREATED: 'COMMENT_CREATED',
	COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',

	MILESTONES_RECEIVED: 'MILESTONES_RECEIVED',
	MILESTONE_CREATED: 'MILESTONE_CREATED',

	VENUES_RECEIVED: 'VENUES_RECEIVED',
	TEAM_RECEIVED: 'TEAM_RECEIVED',
	TEAMS_RECEIVED: 'TEAMS_RECEIVED',
	PROFILE_TEAMS_RECEIVED: 'PROFILE_TEAMS_RECEIVED',
	TEAM_CREATED: 'TEAM_CREATED',
	TEAM_UPDATED: 'TEAM_UPDATED',
	SET_CURRENT_TEAM: 'SET_CURRENT_TEAM',

	LOCATION_CHANGED: 'LOCATION_CHANGED',
	FETCH_DISTRICT: 'FETCH_DISTRICT',
	DISTRICT_CHANGED: 'DISTRICT_CHANGED',
	SELECTED_FEED_CHANGED: 'SELECTED_FEED_CHANGED',

	TOGGLE_LOADER: 'TOGGLE_LOADER',
	TOGGLE_SHOW_MAP: 'TOGGLE_SHOW_MAP',

	FEED_TYPE_ALL: 'all',
	FEED_TYPE_EVENT: 'event',
	FEED_TYPE_NEWS: 'news',
	FEED_TYPE_TEAM: 'team',
	FEED_TYPE_CHAT: 'chat'

}