export default {
	CURRENT_USER_RECIEVED: 'CURRENT_USER_RECIEVED',
	
	PROFILES_RECEIVED: 'PROFILES_RECEIVED',

	POSTS_RECEIVED: 'POSTS_RECEIVED',
	POST_CREATED: 'POST_CREATED',

	COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',

	VENUES_RECEIVED: 'VENUES_RECEIVED',
	TEAMS_RECEIVED: 'TEAMS_RECEIVED',
	TEAM_CREATED: 'TEAM_CREATED',
	
	LOCATION_CHANGED: 'LOCATION_CHANGED',
	DISTRICT_CHANGED: 'DISTRICT_CHANGED',
	SELECTED_FEED_CHANGED: 'SELECTED_FEED_CHANGED',

	TOGGLE_LOADER: 'TOGGLE_LOADER',

	FEED_TYPE_EVENT: 'event',
	FEED_TYPE_NEWS: 'news',
	FEED_TYPE_TEAM: 'team',
	FEED_TYPE_CHAT: 'chat'

}