export default {
	CURRENT_USER_RECIEVED: 'CURRENT_USER_RECIEVED',
	
	POSTS_RECEIVED: 'POSTS_RECEIVED',

	VENUES_RECEIVED: 'VENUES_RECEIVED',
	TEAMS_RECEIVED: 'TEAMS_RECEIVED',
	
	LOCATION_CHANGED: 'LOCATION_CHANGED',
	DISTRICT_CHANGED: 'DISTRICT_CHANGED',
	SELECTED_FEED_CHANGED: 'SELECTED_FEED_CHANGED',

	TOGGLE_LOADER: 'TOGGLE_LOADER',

	FEED_TYPE_EVENT: 'event',
	FEED_TYPE_NEWS: 'news',
	FEED_TYPE_TEAM: 'team'

}